// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxgppqvyvgbczavdcbfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4Z3BwcXZ5dmdiY3phdmRjYmZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDM5NjMsImV4cCI6MjA3MDQxOTk2M30.Mh0Vt5R0N0tglEhsljyDd4ceCHhAQuhiEz4fTQ3agCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});